# entities.py - Entity name databases for semantic highlighting (pure data, no logic)

# Titles & Roles (comprehensive - will be followed by a name)
TITLES = {
    # === POLITICAL LEADERS ===
    "president", "vice president", "president-elect",
    "prime minister", "premier", "deputy prime minister",
    "chancellor", "vice chancellor",
    "chief minister", "first minister",
    # === CABINET & MINISTERS ===
    "minister", "secretary", "undersecretary", "deputy minister",
    "foreign minister", "defense minister", "defence minister",
    "finance minister", "interior minister", "home secretary",
    "foreign secretary", "treasury secretary", "attorney general",
    "solicitor general", "secretary of state", "secretary general",
    # === LEGISLATORS ===
    "senator", "congressman", "congresswoman", "representative",
    "assemblyman", "assemblywoman", "delegate", "councillor", "councilor",
    "speaker", "majority leader", "minority leader", "whip",
    "mp", "member of parliament", "mep", "lawmaker", "legislator",
    # === REGIONAL/LOCAL ===
    "governor", "lieutenant governor", "mayor", "deputy mayor",
    "city manager", "county executive", "prefect", "magistrate",
    # === ROYALTY & NOBILITY ===
    "king", "queen", "prince", "princess", "crown prince", "crown princess",
    "emperor", "empress", "sultan", "emir", "sheikh", "sheik",
    "duke", "duchess", "earl", "countess", "baron", "baroness",
    "lord", "lady", "sir", "dame", "count",
    # === RELIGIOUS LEADERS ===
    "pope", "cardinal", "archbishop", "bishop", "priest", "reverend",
    "pastor", "rabbi", "imam", "ayatollah", "grand ayatollah",
    "patriarch", "dalai lama", "grand mufti", "cleric",
    # === MILITARY RANKS ===
    "general", "lieutenant general", "major general", "brigadier general",
    "brigadier", "colonel", "lieutenant colonel", "major",
    "captain", "lieutenant", "first lieutenant", "second lieutenant",
    "sergeant", "corporal", "private",
    "admiral", "vice admiral", "rear admiral", "commodore",
    "fleet admiral", "field marshal", "marshal",
    "commander", "chief of staff", "commandant",
    # === JUDICIAL ===
    "judge", "justice", "chief justice", "associate justice",
    "magistrate", "prosecutor", "district attorney", "da",
    "public defender", "solicitor", "barrister", "advocate",
    # === DIPLOMATIC ===
    "ambassador", "envoy", "consul", "diplomat", "attach\u00e9",
    "high commissioner", "charg\u00e9 d'affaires", "representative",
    "special envoy", "special representative",
    # === CORPORATE ===
    "ceo", "cfo", "coo", "cto", "cio",
    "chief executive", "chief executive officer",
    "chairman", "chairwoman", "chairperson", "chair",
    "president", "vice president", "vp", "evp", "svp",
    "director", "managing director", "executive director",
    "founder", "co-founder", "partner", "managing partner",
    "treasurer", "comptroller",
    # === ACADEMIC ===
    "professor", "prof", "doctor", "dr",
    "dean", "provost", "chancellor", "rector", "principal",
    "researcher", "scientist", "fellow",
    # === MEDIA ===
    "editor", "editor-in-chief", "publisher", "correspondent",
    "anchor", "journalist", "reporter", "columnist",
    # === LAW ENFORCEMENT ===
    "chief", "police chief", "sheriff", "deputy",
    "commissioner", "superintendent", "inspector",
    "detective", "officer", "constable", "marshal",
    "special agent", "agent",
    # === INTELLIGENCE ===
    "spy", "spymaster", "station chief",
    # === GENERAL LEADERSHIP ===
    "leader", "head", "chief", "boss", "czar", "tsar",
    "spokesperson", "spokesman", "spokeswoman", "representative",
    "coordinator", "advisor", "adviser", "counsel", "aide",
    "official", "executive", "administrator", "commissioner",
}

# Heads of State & Notable Leaders (current + recent, with name variants)
KNOWN_PEOPLE = {
    # === UNITED STATES - PRESIDENTS (All 46) ===
    "biden", "joe biden", "joseph biden", "president biden", "joseph r biden",
    "trump", "donald trump", "president trump", "donald j trump",
    "obama", "barack obama", "president obama", "barack hussein obama",
    "bush", "george bush", "george w bush", "president bush", "george h w bush", "bush sr", "bush jr",
    "clinton", "bill clinton", "president clinton", "william clinton",
    "reagan", "ronald reagan", "president reagan", "the gipper",
    "carter", "jimmy carter", "president carter", "james earl carter",
    "nixon", "richard nixon", "president nixon", "tricky dick",
    "ford", "gerald ford", "president ford",
    "kennedy", "john f kennedy", "jfk", "president kennedy", "john kennedy", "jack kennedy",
    "johnson", "lyndon johnson", "lbj", "lyndon b johnson",
    "eisenhower", "dwight eisenhower", "ike", "dwight d eisenhower",
    "truman", "harry truman", "president truman", "harry s truman",
    "roosevelt", "franklin roosevelt", "fdr", "franklin d roosevelt",
    "theodore roosevelt", "teddy roosevelt", "tr",
    "hoover", "herbert hoover", "president hoover",
    "coolidge", "calvin coolidge", "silent cal",
    "harding", "warren harding", "warren g harding",
    "wilson", "woodrow wilson", "president wilson",
    "taft", "william taft", "william howard taft",
    "mckinley", "william mckinley", "president mckinley",
    "cleveland", "grover cleveland",
    "harrison", "benjamin harrison", "william henry harrison",
    "arthur", "chester arthur", "chester a arthur",
    "garfield", "james garfield", "james a garfield",
    "hayes", "rutherford hayes", "rutherford b hayes",
    "grant", "ulysses grant", "ulysses s grant", "general grant",
    "andrew johnson", "president johnson",
    "lincoln", "abraham lincoln", "abe lincoln", "president lincoln", "honest abe",
    "buchanan", "james buchanan",
    "pierce", "franklin pierce",
    "fillmore", "millard fillmore",
    "taylor", "zachary taylor",
    "polk", "james polk", "james k polk",
    "tyler", "john tyler",
    "van buren", "martin van buren",
    "jackson", "andrew jackson", "old hickory",
    "adams", "john adams", "john quincy adams", "samuel adams",
    "jefferson", "thomas jefferson", "president jefferson",
    "washington", "george washington", "president washington", "general washington",

    # === UNITED STATES - FOUNDING FATHERS & EARLY LEADERS ===
    "benjamin franklin", "ben franklin", "franklin",
    "alexander hamilton", "hamilton",
    "james madison", "madison",
    "james monroe", "monroe",
    "john jay",
    "patrick henry",
    "paul revere",
    "john hancock",
    "thomas paine",
    "aaron burr", "burr",
    "betsy ross",

    # === UNITED STATES - CIVIL WAR ERA ===
    "robert e lee", "general lee", "lee",
    "stonewall jackson", "thomas jackson",
    "ulysses s grant", "general grant",
    "william sherman", "general sherman", "sherman",
    "jefferson davis",
    "john brown",
    "harriet tubman", "tubman",
    "frederick douglass", "douglass",
    "clara barton",
    "sojourner truth",

    # === UNITED STATES - CIVIL RIGHTS LEADERS ===
    "martin luther king", "mlk", "dr king", "martin luther king jr", "reverend king",
    "rosa parks",
    "malcolm x", "malcolm little", "el-hajj malik el-shabazz",
    "john lewis", "congressman lewis",
    "medgar evers",
    "thurgood marshall", "justice marshall",
    "booker t washington",
    "w e b du bois", "du bois",
    "ida b wells",
    "jesse jackson", "reverend jackson",
    "al sharpton", "reverend sharpton",
    "coretta scott king",
    "ralph abernathy",
    "stokely carmichael",
    "huey newton",
    "angela davis",
    "cesar chavez",
    "dolores huerta",

    # === UNITED STATES - SUPREME COURT JUSTICES ===
    "john roberts", "chief justice roberts", "roberts",
    "clarence thomas", "justice thomas",
    "samuel alito", "justice alito", "alito",
    "sonia sotomayor", "justice sotomayor", "sotomayor",
    "elena kagan", "justice kagan", "kagan",
    "neil gorsuch", "justice gorsuch", "gorsuch",
    "brett kavanaugh", "justice kavanaugh", "kavanaugh",
    "amy coney barrett", "justice barrett", "barrett",
    "ketanji brown jackson", "justice jackson",
    "ruth bader ginsburg", "rbg", "justice ginsburg", "ginsburg",
    "antonin scalia", "justice scalia", "scalia",
    "anthony kennedy", "justice kennedy",
    "sandra day oconnor", "oconnor",
    "john paul stevens",
    "david souter",
    "earl warren", "chief justice warren",

    # === UNITED STATES - VICE PRESIDENTS & FIRST LADIES ===
    "kamala harris", "harris", "vice president harris",
    "mike pence", "pence", "vice president pence",
    "dick cheney", "cheney", "vice president cheney",
    "al gore", "gore", "vice president gore",
    "dan quayle", "quayle",
    "walter mondale", "mondale",
    "nelson rockefeller",
    "spiro agnew", "agnew",
    "hubert humphrey", "humphrey",
    "hillary clinton", "hillary rodham clinton", "secretary clinton",
    "michelle obama", "first lady obama",
    "melania trump", "first lady trump",
    "jill biden", "dr jill biden",
    "laura bush", "first lady bush",
    "barbara bush",
    "nancy reagan", "first lady reagan",
    "jacqueline kennedy", "jackie kennedy", "jackie o",
    "eleanor roosevelt", "first lady roosevelt",

    # === UNITED STATES - CABINET & KEY OFFICIALS ===
    "blinken", "antony blinken", "secretary blinken",
    "pompeo", "mike pompeo", "secretary pompeo",
    "tillerson", "rex tillerson",
    "kerry", "john kerry", "secretary kerry",
    "hillary clinton", "secretary clinton",
    "condoleezza rice", "condi rice", "secretary rice",
    "colin powell", "general powell", "secretary powell",
    "madeleine albright", "secretary albright",
    "austin", "lloyd austin", "secretary austin",
    "mattis", "james mattis", "general mattis", "mad dog mattis",
    "esper", "mark esper",
    "rumsfeld", "donald rumsfeld", "secretary rumsfeld",
    "yellen", "janet yellen", "secretary yellen",
    "mnuchin", "steven mnuchin",
    "geithner", "timothy geithner",
    "paulson", "hank paulson", "henry paulson",
    "garland", "merrick garland", "attorney general garland",
    "barr", "william barr", "bill barr", "attorney general barr",
    "sessions", "jeff sessions", "attorney general sessions",
    "holder", "eric holder", "attorney general holder",
    "comey", "james comey", "director comey",
    "mueller", "robert mueller", "special counsel mueller",

    # === UNITED STATES - MILITARY LEADERS ===
    "general milley", "mark milley", "milley",
    "general petraeus", "david petraeus", "petraeus",
    "general mcchrystal", "stanley mcchrystal",
    "norman schwarzkopf", "stormin norman",
    "wesley clark",
    "douglas macarthur", "general macarthur", "macarthur",
    "george patton", "general patton", "patton",
    "omar bradley", "general bradley",
    "chester nimitz", "admiral nimitz",
    "john pershing", "general pershing", "black jack pershing",

    # === UNITED STATES - CONGRESSIONAL LEADERS ===
    "pelosi", "nancy pelosi", "speaker pelosi",
    "mccarthy", "kevin mccarthy", "speaker mccarthy",
    "johnson", "mike johnson", "speaker johnson",
    "schumer", "chuck schumer", "senator schumer", "majority leader schumer",
    "mcconnell", "mitch mcconnell", "senator mcconnell", "minority leader mcconnell",
    "aoc", "alexandria ocasio-cortez", "ocasio-cortez",
    "bernie sanders", "sanders", "senator sanders",
    "elizabeth warren", "warren", "senator warren",
    "ted cruz", "cruz", "senator cruz",
    "marco rubio", "rubio", "senator rubio",
    "mitt romney", "romney", "senator romney",
    "rand paul", "senator paul",
    "lindsey graham", "graham", "senator graham",
    "joe manchin", "manchin", "senator manchin",
    "kyrsten sinema", "sinema",
    "adam schiff", "schiff", "representative schiff",
    "jim jordan", "jordan", "representative jordan",
    "marjorie taylor greene", "mtg",
    "matt gaetz", "gaetz",
    "newt gingrich", "gingrich", "speaker gingrich",
    "tip oneill", "oneill",
    "bob dole", "dole", "senator dole",
    "john mccain", "mccain", "senator mccain",
    "ted kennedy", "senator kennedy",
    "robert kennedy", "rfk", "bobby kennedy",

    # === UNITED STATES - GOVERNORS & STATE LEADERS ===
    "desantis", "ron desantis", "governor desantis",
    "newsom", "gavin newsom", "governor newsom",
    "abbott", "greg abbott", "governor abbott",
    "cuomo", "andrew cuomo", "governor cuomo",
    "hochul", "kathy hochul", "governor hochul",
    "pritzker", "jb pritzker",
    "whitmer", "gretchen whitmer", "governor whitmer",
    "kemp", "brian kemp",
    "noem", "kristi noem",
    "haley", "nikki haley", "ambassador haley",
    "polis", "jared polis",
    "schwarzenegger", "arnold schwarzenegger", "governor schwarzenegger",
    "jerry brown", "governor brown",
    "rudy giuliani", "giuliani", "mayor giuliani",
    "bloomberg", "michael bloomberg", "mayor bloomberg",
    "de blasio", "bill de blasio",
    "eric adams", "mayor adams",

    # === UNITED STATES - OTHER NOTABLE FIGURES ===
    "elon musk", "musk",
    "jeff bezos", "bezos",
    "mark zuckerberg", "zuckerberg", "zuck",
    "bill gates", "gates",
    "warren buffett", "buffett",
    "steve jobs", "jobs",
    "tim cook",
    "sam altman",
    "henry kissinger", "kissinger", "secretary kissinger",
    "zbigniew brzezinski", "brzezinski",
    "george soros", "soros",
    "koch", "charles koch", "david koch", "koch brothers",
    "rupert murdoch", "murdoch",
    "oprah", "oprah winfrey",
    "tucker carlson", "carlson",
    "sean hannity", "hannity",
    "rachel maddow", "maddow",
    "alex jones",
    "rush limbaugh", "limbaugh",
    "bob woodward", "woodward",
    "carl bernstein", "bernstein",
    "edward snowden", "snowden",
    "julian assange", "assange",
    "chelsea manning", "manning",

    # === UNITED KINGDOM (Monarchs, PMs) ===
    "king charles", "charles iii", "king charles iii",
    "queen elizabeth", "elizabeth ii", "queen elizabeth ii",
    "prince william", "william", "prince of wales",
    "prince harry", "harry", "duke of sussex",
    "kate middleton", "catherine", "princess of wales",
    "meghan markle", "meghan", "duchess of sussex",
    "starmer", "keir starmer", "prime minister starmer", "sir keir starmer",
    "sunak", "rishi sunak", "prime minister sunak",
    "truss", "liz truss", "prime minister truss",
    "boris johnson", "johnson", "prime minister johnson",
    "theresa may", "may", "prime minister may",
    "david cameron", "cameron", "prime minister cameron",
    "gordon brown", "brown", "prime minister brown",
    "tony blair", "blair", "prime minister blair",
    "john major", "major",
    "thatcher", "margaret thatcher", "prime minister thatcher", "baroness thatcher",

    # === CANADA ===
    "trudeau", "justin trudeau", "prime minister trudeau", "pierre trudeau",
    "harper", "stephen harper",
    "chretien", "jean chretien",
    "mulroney", "brian mulroney",
    "poilievre", "pierre poilievre",

    # === FRANCE ===
    "macron", "emmanuel macron", "president macron",
    "hollande", "francois hollande", "president hollande",
    "sarkozy", "nicolas sarkozy", "president sarkozy",
    "chirac", "jacques chirac",
    "mitterrand", "francois mitterrand",
    "de gaulle", "charles de gaulle", "general de gaulle",
    "le pen", "marine le pen", "jean-marie le pen",
    "melenchon", "jean-luc melenchon",
    "attal", "gabriel attal", "prime minister attal",
    "borne", "elisabeth borne",

    # === GERMANY ===
    "scholz", "olaf scholz", "chancellor scholz",
    "merkel", "angela merkel", "chancellor merkel",
    "schroeder", "gerhard schroeder", "chancellor schroeder",
    "kohl", "helmut kohl", "chancellor kohl",
    "steinmeier", "frank-walter steinmeier", "president steinmeier",
    "habeck", "robert habeck",
    "lindner", "christian lindner",
    "baerbock", "annalena baerbock",

    # === ITALY ===
    "meloni", "giorgia meloni", "prime minister meloni",
    "draghi", "mario draghi", "prime minister draghi",
    "conte", "giuseppe conte",
    "berlusconi", "silvio berlusconi",
    "renzi", "matteo renzi",
    "salvini", "matteo salvini",
    "mattarella", "sergio mattarella", "president mattarella",

    # === SPAIN ===
    "sanchez", "pedro sanchez", "prime minister sanchez",
    "rajoy", "mariano rajoy",
    "zapatero", "jose luis zapatero",
    "felipe vi", "king felipe",

    # === OTHER WESTERN EUROPE ===
    "rutte", "mark rutte", "prime minister rutte",
    "wilders", "geert wilders",
    "de croo", "alexander de croo",
    "bettel", "xavier bettel",
    "ammann", "alain berset", "viola amherd",
    "nehammer", "karl nehammer",
    "kurz", "sebastian kurz",
    "costa", "antonio costa",
    "rebelo de sousa", "marcelo rebelo de sousa",

    # === NORDIC COUNTRIES ===
    "frederiksen", "mette frederiksen",
    "kristersson", "ulf kristersson",
    "andersson", "magdalena andersson",
    "store", "jonas gahr store",
    "solberg", "erna solberg",
    "marin", "sanna marin",
    "stubb", "alexander stubb",
    "orpo", "petteri orpo",
    "niinisto", "sauli niinisto",

    # === EASTERN EUROPE ===
    "zelensky", "zelenskyy", "volodymyr zelensky", "president zelensky", "volodymyr zelenskyy",
    "poroshenko", "petro poroshenko",
    "yanukovych", "viktor yanukovych",
    "tymoshenko", "yulia tymoshenko",
    "duda", "andrzej duda", "president duda",
    "morawiecki", "mateusz morawiecki",
    "tusk", "donald tusk", "prime minister tusk",
    "kaczynski", "jaroslaw kaczynski", "lech kaczynski",
    "orban", "viktor orban", "prime minister orban",
    "fiala", "petr fiala",
    "babis", "andrej babis",
    "zeman", "milos zeman",
    "havel", "vaclav havel",
    "fico", "robert fico",
    "iohannis", "klaus iohannis",
    "radev", "rumen radev",
    "vucic", "aleksandar vucic",
    "plenkovic", "andrej plenkovic",
    "pahor", "borut pahor",
    "rama", "edi rama",
    "milo", "milo djukanovic",

    # === RUSSIA & FORMER USSR ===
    "putin", "vladimir putin", "president putin", "vladimir vladimirovich putin",
    "medvedev", "dmitry medvedev", "prime minister medvedev",
    "lavrov", "sergey lavrov", "foreign minister lavrov", "sergei lavrov",
    "shoigu", "sergei shoigu", "defense minister shoigu",
    "gerasimov", "valery gerasimov",
    "prigozhin", "yevgeny prigozhin",
    "navalny", "alexei navalny", "aleksei navalny",
    "gorbachev", "mikhail gorbachev", "president gorbachev",
    "yeltsin", "boris yeltsin", "president yeltsin",
    "khrushchev", "nikita khrushchev",
    "stalin", "joseph stalin",
    "lenin", "vladimir lenin",
    "lukashenko", "alexander lukashenko", "president lukashenko", "alyaksandr lukashenko",
    "tokayev", "kassym-jomart tokayev",
    "nazarbayev", "nursultan nazarbayev",
    "mirziyoyev", "shavkat mirziyoyev",
    "aliyev", "ilham aliyev",
    "pashinyan", "nikol pashinyan",
    "garibashvili", "irakli garibashvili",
    "saakashvili", "mikheil saakashvili",

    # === CHINA ===
    "xi", "xi jinping", "president xi", "chairman xi", "xi jin ping",
    "li qiang", "premier li qiang", "prime minister li",
    "li keqiang", "premier li keqiang",
    "wang yi", "foreign minister wang",
    "hu jintao", "president hu",
    "jiang zemin", "president jiang",
    "deng xiaoping", "deng",
    "mao", "mao zedong", "chairman mao", "mao tse-tung",
    "zhou enlai", "premier zhou",
    "wen jiabao", "premier wen",

    # === JAPAN ===
    "kishida", "fumio kishida", "prime minister kishida",
    "suga", "yoshihide suga", "prime minister suga",
    "abe", "shinzo abe", "prime minister abe",
    "koizumi", "junichiro koizumi",
    "emperor naruhito", "naruhito",
    "emperor akihito", "akihito",

    # === KOREA ===
    "yoon", "yoon suk yeol", "president yoon", "yoon suk-yeol",
    "moon", "moon jae-in", "president moon",
    "park geun-hye", "park",
    "lee myung-bak",
    "kim jong un", "kim jong-un", "jong un", "chairman kim",
    "kim jong il", "kim il sung",

    # === INDIA ===
    "modi", "narendra modi", "prime minister modi", "pm modi",
    "gandhi", "rahul gandhi", "sonia gandhi", "indira gandhi", "rajiv gandhi", "mahatma gandhi",
    "singh", "manmohan singh", "prime minister singh",
    "vajpayee", "atal bihari vajpayee",
    "murmu", "droupadi murmu", "president murmu",
    "kovind", "ram nath kovind",
    "shah", "amit shah", "home minister shah",
    "jaishankar", "s jaishankar",

    # === PAKISTAN ===
    "sharif", "nawaz sharif", "shehbaz sharif", "prime minister sharif",
    "khan", "imran khan", "prime minister khan",
    "bhutto", "benazir bhutto", "zulfikar ali bhutto", "bilawal bhutto",
    "zardari", "asif ali zardari",
    "musharraf", "pervez musharraf",

    # === SOUTHEAST ASIA ===
    "marcos", "bongbong marcos", "ferdinand marcos jr", "ferdinand marcos",
    "duterte", "rodrigo duterte", "president duterte",
    "aquino", "benigno aquino", "corazon aquino",
    "jokowi", "joko widodo", "president jokowi",
    "prabowo", "prabowo subianto",
    "yudhoyono", "susilo bambang yudhoyono",
    "anwar", "anwar ibrahim", "prime minister anwar",
    "mahathir", "mahathir mohamad",
    "lee hsien loong", "prime minister lee",
    "lee kuan yew",
    "prayuth", "prayuth chan-ocha",
    "thaksin", "thaksin shinawatra",
    "hun sen", "prime minister hun sen",
    "hun manet",
    "aung san suu kyi", "suu kyi",
    "min aung hlaing",

    # === MIDDLE EAST - ISRAEL ===
    "netanyahu", "benjamin netanyahu", "bibi", "prime minister netanyahu", "bibi netanyahu",
    "gantz", "benny gantz",
    "lapid", "yair lapid",
    "bennett", "naftali bennett",
    "herzog", "isaac herzog", "president herzog",
    "ben-gvir", "itamar ben-gvir",
    "smotrich", "bezalel smotrich",
    "sharon", "ariel sharon",
    "olmert", "ehud olmert",
    "barak", "ehud barak",
    "peres", "shimon peres",
    "rabin", "yitzhak rabin",
    "begin", "menachem begin",
    "ben-gurion", "david ben-gurion",

    # === MIDDLE EAST - PALESTINE ===
    "abbas", "mahmoud abbas", "president abbas", "abu mazen",
    "arafat", "yasser arafat",
    "haniyeh", "ismail haniyeh",
    "sinwar", "yahya sinwar",
    "meshaal", "khaled meshaal",

    # === MIDDLE EAST - IRAN ===
    "khamenei", "ali khamenei", "ayatollah khamenei", "supreme leader khamenei",
    "raisi", "ebrahim raisi", "president raisi",
    "rouhani", "hassan rouhani",
    "ahmadinejad", "mahmoud ahmadinejad",
    "khatami", "mohammad khatami",
    "khomeini", "ayatollah khomeini", "ruhollah khomeini",
    "zarif", "javad zarif", "mohammad javad zarif",
    "soleimani", "qasem soleimani", "general soleimani",

    # === MIDDLE EAST - TURKEY ===
    "erdogan", "recep tayyip erdogan", "president erdogan", "tayyip erdogan",
    "davutoglu", "ahmet davutoglu",
    "yildirim", "binali yildirim",
    "ataturk", "mustafa kemal ataturk", "kemal ataturk",

    # === MIDDLE EAST - ARAB STATES ===
    "mbs", "mohammed bin salman", "crown prince mohammed", "prince mohammed",
    "king salman", "salman bin abdulaziz", "king salman bin abdulaziz",
    "king abdullah", "abdullah ii",
    "sisi", "abdel fattah el-sisi", "al-sisi", "president sisi",
    "mubarak", "hosni mubarak",
    "morsi", "mohamed morsi",
    "assad", "bashar al-assad", "bashar assad", "president assad",
    "hafez assad", "hafez al-assad",
    "saddam", "saddam hussein",
    "maliki", "nouri al-maliki",
    "abadi", "haider al-abadi",
    "kadhimi", "mustafa al-kadhimi",
    "gaddafi", "muammar gaddafi", "qaddafi", "colonel gaddafi",
    "haftar", "khalifa haftar",
    "houthi", "abdul-malik al-houthi",
    "sheikh mohammed", "mohammed bin rashid", "mbr",
    "tamim", "sheikh tamim", "emir tamim",

    # === AFRICA - NORTH ===
    "tebboune", "abdelmadjid tebboune",
    "bouteflika", "abdelaziz bouteflika",
    "saied", "kais saied",
    "essebsi", "beji caid essebsi",
    "king mohammed vi", "mohammed vi",

    # === AFRICA - SUB-SAHARAN ===
    "ramaphosa", "cyril ramaphosa", "president ramaphosa",
    "zuma", "jacob zuma",
    "mbeki", "thabo mbeki",
    "mandela", "nelson mandela", "madiba",
    "de klerk", "fw de klerk",
    "kagame", "paul kagame", "president kagame",
    "museveni", "yoweri museveni",
    "ruto", "william ruto", "president ruto",
    "kenyatta", "uhuru kenyatta", "jomo kenyatta",
    "tinubu", "bola tinubu", "president tinubu",
    "buhari", "muhammadu buhari",
    "obasanjo", "olusegun obasanjo",
    "jonathan", "goodluck jonathan",
    "abiy", "abiy ahmed", "prime minister abiy",
    "afwerki", "isaias afwerki",
    "bashir", "omar al-bashir",
    "burhan", "abdel fattah al-burhan",
    "hemeti", "mohamed hamdan dagalo",
    "kabila", "joseph kabila", "laurent kabila",
    "tshisekedi", "felix tshisekedi",
    "mnangagwa", "emmerson mnangagwa",
    "mugabe", "robert mugabe",
    "dos santos", "jose eduardo dos santos",
    "lourenco", "joao lourenco",
    "deby", "idriss deby", "mahamat deby",
    "keita", "ibrahim boubacar keita",
    "goita", "assimi goita",
    "ouattara", "alassane ouattara",
    "akufo-addo", "nana akufo-addo",
    "mahama", "john mahama",
    "macky sall", "sall",
    "conde", "alpha conde",

    # === LATIN AMERICA ===
    "lula", "lula da silva", "luiz inacio lula da silva", "president lula",
    "bolsonaro", "jair bolsonaro", "president bolsonaro",
    "rousseff", "dilma rousseff",
    "temer", "michel temer",
    "cardoso", "fernando henrique cardoso",
    "amlo", "lopez obrador", "andres manuel lopez obrador",
    "calderon", "felipe calderon",
    "pena nieto", "enrique pena nieto",
    "sheinbaum", "claudia sheinbaum",
    "milei", "javier milei", "president milei",
    "fernandez", "alberto fernandez", "cristina fernandez", "cristina kirchner",
    "macri", "mauricio macri",
    "kirchner", "nestor kirchner",
    "maduro", "nicolas maduro", "president maduro",
    "chavez", "hugo chavez", "president chavez",
    "guaido", "juan guaido",
    "petro", "gustavo petro", "president petro",
    "duque", "ivan duque",
    "santos", "juan manuel santos",
    "uribe", "alvaro uribe",
    "boric", "gabriel boric", "president boric",
    "pinera", "sebastian pinera",
    "bachelet", "michelle bachelet",
    "castillo", "pedro castillo",
    "boluarte", "dina boluarte",
    "morales", "evo morales",
    "arce", "luis arce",
    "correa", "rafael correa",
    "noboa", "daniel noboa",
    "bukele", "nayib bukele", "president bukele",
    "ortega", "daniel ortega",
    "castro", "fidel castro", "raul castro", "miguel diaz-canel", "diaz-canel",
    "aristide", "jean-bertrand aristide",

    # === OCEANIA ===
    "albanese", "anthony albanese", "prime minister albanese",
    "morrison", "scott morrison",
    "turnbull", "malcolm turnbull",
    "abbott", "tony abbott",
    "gillard", "julia gillard",
    "rudd", "kevin rudd",
    "howard", "john howard",
    "luxon", "christopher luxon",
    "ardern", "jacinda ardern", "prime minister ardern",
    "hipkins", "chris hipkins",

    # === INTERNATIONAL ORGANIZATIONS ===
    "guterres", "antonio guterres", "secretary general guterres", "un secretary general",
    "ban ki-moon", "ban", "secretary general ban",
    "kofi annan", "annan",
    "stoltenberg", "jens stoltenberg", "secretary general stoltenberg",
    "von der leyen", "ursula von der leyen", "president von der leyen",
    "michel", "charles michel",
    "lagarde", "christine lagarde", "ecb president lagarde",
    "draghi", "mario draghi",
    "georgieva", "kristalina georgieva",
    "okonjo-iweala", "ngozi okonjo-iweala",
    "tedros", "tedros adhanom", "dr tedros",

    # === RELIGIOUS LEADERS ===
    "pope francis", "francis", "pope",
    "pope benedict", "benedict xvi", "joseph ratzinger",
    "pope john paul", "john paul ii", "karol wojtyla",
    "dalai lama", "tenzin gyatso",
    "patriarch kirill", "kirill",
    "archbishop welby", "justin welby",

    # === MAJOR HISTORICAL FIGURES (20th century, still referenced) ===
    "churchill", "winston churchill",
    "hitler", "adolf hitler",
    "mussolini", "benito mussolini",
    "franco", "francisco franco",
    "tito", "josip broz tito",
    "ceausescu", "nicolae ceausescu",
    "pinochet", "augusto pinochet",
    "pol pot",
    "ho chi minh",
    "sukarno", "suharto",
    "nasser", "gamal abdel nasser",
    "sadat", "anwar sadat",
}

# Countries & Nations (all 195 UN members + common aliases + territories)
COUNTRIES = {
    # North America
    "united states", "america", "usa", "u.s.", "canada", "mexico",
    # Central America
    "guatemala", "belize", "honduras", "el salvador", "nicaragua", "costa rica", "panama",
    # Caribbean
    "cuba", "haiti", "dominican republic", "jamaica", "bahamas", "barbados",
    "trinidad and tobago", "trinidad", "tobago", "grenada", "saint lucia", "st lucia",
    "antigua and barbuda", "antigua", "saint kitts and nevis", "saint vincent",
    "dominica", "puerto rico",
    # South America
    "brazil", "argentina", "colombia", "venezuela", "peru", "chile", "ecuador",
    "bolivia", "paraguay", "uruguay", "guyana", "suriname", "french guiana",
    # Western Europe
    "united kingdom", "britain", "england", "scotland", "wales", "northern ireland",
    "france", "germany", "italy", "spain", "portugal", "netherlands", "belgium",
    "luxembourg", "switzerland", "austria", "ireland", "monaco", "andorra",
    "liechtenstein", "san marino", "vatican",
    # Northern Europe
    "sweden", "norway", "finland", "denmark", "iceland", "greenland",
    # Eastern Europe
    "russia", "ukraine", "poland", "romania", "czech republic", "czechia",
    "hungary", "bulgaria", "slovakia", "belarus", "moldova", "lithuania",
    "latvia", "estonia",
    # Balkans
    "serbia", "croatia", "bosnia", "bosnia and herzegovina", "slovenia",
    "north macedonia", "macedonia", "albania", "montenegro", "kosovo", "greece",
    # Central Asia
    "kazakhstan", "uzbekistan", "turkmenistan", "kyrgyzstan", "tajikistan",
    "afghanistan", "mongolia",
    # East Asia
    "china", "japan", "south korea", "north korea", "korea", "taiwan", "hong kong", "macau",
    # Southeast Asia
    "vietnam", "thailand", "philippines", "indonesia", "malaysia", "singapore",
    "myanmar", "burma", "cambodia", "laos", "brunei", "east timor", "timor-leste",
    # South Asia
    "india", "pakistan", "bangladesh", "sri lanka", "nepal", "bhutan", "maldives",
    # Middle East
    "iran", "iraq", "israel", "palestine", "gaza", "syria", "turkey", "lebanon",
    "jordan", "saudi arabia", "yemen", "oman", "uae", "united arab emirates", "emirates",
    "qatar", "bahrain", "kuwait", "cyprus",
    # Caucasus
    "georgia", "armenia", "azerbaijan",
    # North Africa
    "egypt", "libya", "tunisia", "algeria", "morocco", "western sahara",
    # East Africa
    "ethiopia", "kenya", "tanzania", "uganda", "rwanda", "burundi", "somalia",
    "south sudan", "sudan", "eritrea", "djibouti", "seychelles", "mauritius",
    # West Africa
    "nigeria", "ghana", "senegal", "ivory coast", "cote d'ivoire", "mali",
    "burkina faso", "niger", "guinea", "benin", "togo", "sierra leone", "liberia",
    "mauritania", "gambia", "guinea-bissau", "cape verde",
    # Central Africa
    "congo", "democratic republic of congo", "drc", "cameroon", "gabon",
    "central african republic", "chad", "equatorial guinea", "sao tome",
    # Southern Africa
    "south africa", "zimbabwe", "zambia", "botswana", "namibia", "mozambique",
    "angola", "malawi", "lesotho", "eswatini", "swaziland", "madagascar",
    # Oceania
    "australia", "new zealand", "papua new guinea", "fiji", "solomon islands",
    "vanuatu", "samoa", "tonga", "kiribati", "micronesia", "palau", "marshall islands",
    "nauru", "tuvalu",
    # Historical
    "soviet union", "ussr", "yugoslavia", "czechoslovakia",
}

# Government & Politics (comprehensive)
GOVERNMENT_TERMS = {
    # === US GOVERNMENT ===
    # Executive
    "white house", "oval office", "executive branch",
    "state department", "department of state", "treasury department",
    "defense department", "department of defense", "dod", "pentagon",
    "justice department", "department of justice", "doj",
    "homeland security", "department of homeland security", "dhs",
    "interior department", "department of interior",
    "commerce department", "department of commerce",
    "labor department", "department of labor",
    "hhs", "health and human services", "department of education",
    "department of energy", "doe", "department of agriculture", "usda",
    "department of transportation", "dot", "hud",
    "department of veterans affairs", "va",
    # US Agencies
    "fbi", "federal bureau of investigation", "cia", "central intelligence agency",
    "nsa", "national security agency", "dea", "atf", "secret service",
    "us marshals", "ice", "cbp", "customs and border protection",
    "tsa", "fema", "coast guard",
    "sec", "securities and exchange commission",
    "ftc", "federal trade commission", "fcc", "federal communications commission",
    "epa", "environmental protection agency", "fda", "food and drug administration",
    "cdc", "centers for disease control", "nih", "national institutes of health",
    "faa", "federal aviation administration", "nasa",
    "federal reserve", "fed", "treasury", "irs", "internal revenue service",
    "usps", "postal service", "social security administration", "ssa",
    "national weather service", "nws", "noaa",
    # US Legislative
    "congress", "senate", "house of representatives", "house",
    "capitol", "capitol hill", "congressional",
    # US Judicial
    "supreme court", "federal court", "appeals court", "circuit court",
    "district court",
    # US Political
    "democratic party", "democrats", "dnc",
    "republican party", "republicans", "gop", "rnc",
    "libertarian party", "green party",
    # US State/Local
    "governor", "state legislature", "city council", "mayor",
    # === UK GOVERNMENT ===
    "parliament", "house of commons", "house of lords", "westminster",
    "downing street", "10 downing street", "cabinet office", "privy council",
    "home office", "foreign office", "treasury", "ministry of defence", "mod",
    "nhs", "national health service", "mi5", "mi6", "gchq",
    "scotland yard", "met police", "metropolitan police",
    "labour party", "labour", "conservative party", "conservatives", "tories",
    "liberal democrats", "lib dems", "snp", "scottish national party",
    # === EU INSTITUTIONS ===
    "european commission", "european parliament", "european council",
    "council of the european union", "european court of justice", "ecj",
    "european central bank", "ecb", "eurogroup", "frontex",
    # === RUSSIAN GOVERNMENT ===
    "kremlin", "duma", "state duma", "federation council",
    "fsb", "federal security service", "svr", "gru",
    "ministry of defence", "ministry of foreign affairs",
    "united russia", "communist party of russia",
    # === CHINESE GOVERNMENT ===
    "communist party", "ccp", "cpc", "politburo", "standing committee",
    "central committee", "national people's congress", "npc",
    "state council", "central military commission", "cmc",
    "ministry of foreign affairs", "ministry of national defense",
    "ministry of state security", "mss", "ministry of public security",
    "people's bank of china", "pboc",
    # === OTHER GOVERNMENTS ===
    # France
    "elysee", "elysee palace", "national assembly", "french senate",
    # Germany
    "bundestag", "bundesrat", "chancellery",
    "cdu", "csu", "spd", "greens", "afd", "fdp",
    # Japan
    "diet", "national diet", "ldp", "liberal democratic party",
    # India
    "lok sabha", "rajya sabha", "bjp", "congress party", "inc",
    # Brazil
    "planalto", "brazilian congress",
    # General terms
    "parliament", "legislature", "congress", "senate", "assembly",
    "cabinet", "ministry", "department", "agency", "bureau", "office",
    "court", "tribunal", "commission", "council", "committee",
    "defence ministry", "defense ministry", "foreign ministry",
    "interior ministry", "finance ministry", "justice ministry",
    "prime minister's office", "president's office", "chancellery",
    "national security council", "nsc",
    "intelligence agency", "secret service", "security service",
    "central bank", "reserve bank", "monetary authority",
    "electoral commission", "election commission",
    "constitutional court", "high court", "appeals court",
    "prosecutor", "attorney general", "solicitor general",
    "bureau of meteorology", "weather service",
}

# Military & Defense (comprehensive)
MILITARY_TERMS = {
    # === ALLIANCES & COALITIONS ===
    "nato", "north atlantic treaty organization",
    "five eyes", "aukus", "quad", "csto", "sco", "shanghai cooperation",
    # === US MILITARY ===
    "us military", "us armed forces", "american military",
    "us army", "army", "us navy", "navy", "us air force", "air force",
    "us marine corps", "marine corps", "marines", "usmc",
    "us coast guard", "coast guard", "space force", "us space force",
    "national guard", "army national guard", "air national guard",
    "special forces", "green berets", "army rangers", "delta force",
    "navy seals", "seal team", "devgru", "jsoc",
    "joint chiefs", "joint chiefs of staff", "central command", "centcom",
    "indo-pacific command", "indopacom", "european command", "eucom",
    "northern command", "northcom", "southern command", "southcom",
    "africa command", "africom", "cyber command", "strategic command",
    # === RUSSIAN MILITARY ===
    "russian military", "russian armed forces", "russian army",
    "russian navy", "russian air force", "vks",
    "spetsnaz", "gru", "wagner group", "wagner", "pmc wagner",
    "black sea fleet", "northern fleet", "pacific fleet",
    # === CHINESE MILITARY ===
    "pla", "people's liberation army", "chinese military",
    "pla army", "pla navy", "plan", "pla air force", "plaaf",
    "pla rocket force", "plarf", "strategic support force",
    "eastern theater command", "southern theater command",
    # === UK MILITARY ===
    "british military", "british armed forces", "british army",
    "royal navy", "royal air force", "raf", "royal marines",
    "sas", "sbs", "special air service", "special boat service",
    # === OTHER NATIONAL MILITARIES ===
    "idf", "israel defense forces", "israeli military", "mossad", "shin bet",
    "bundeswehr", "german military", "german army",
    "french military", "french army", "foreign legion",
    "indian military", "indian army", "indian navy", "indian air force",
    "jsdf", "japan self-defense forces", "japanese military",
    "rok military", "south korean military", "rok army",
    "turkish military", "turkish armed forces",
    "iranian military", "irgc", "revolutionary guard", "quds force",
    "saudi military", "saudi armed forces",
    "pakistani military", "pakistan army", "isi",
    "ukrainian military", "ukrainian armed forces", "azov",
    # === MILITANT & TERRORIST GROUPS ===
    "hamas", "palestinian islamic jihad", "pij", "fatah", "plo",
    "hezbollah", "houthis", "ansar allah",
    "taliban", "haqqani network",
    "isis", "isil", "islamic state", "daesh", "al-qaeda", "al qaeda",
    "al-shabaab", "boko haram", "jemaah islamiyah",
    "pkk", "kurdish militants", "peshmerga", "ypg", "sdf",
    "ira", "eta", "farc", "eln",
    # === MILITARY UNITS & TERMS ===
    "armed forces", "military", "defense forces", "defence forces",
    "troops", "soldiers", "infantry", "cavalry", "artillery",
    "battalion", "brigade", "division", "regiment", "corps",
    "platoon", "company", "squadron", "fleet", "flotilla",
    "airborne", "paratroopers", "mechanized", "armored",
    "special operations", "commandos", "elite forces",
    "reservists", "reserves", "militia", "paramilitary",
    "mercenaries", "contractors", "private military",
    # === EQUIPMENT TERMS ===
    "fighter jets", "bombers", "drones", "uav", "missiles",
    "tanks", "armored vehicles", "warships", "submarines",
    "aircraft carrier", "destroyer", "frigate", "cruiser",
    "nuclear weapons", "icbm", "ballistic missiles",
}

# Organizations (Companies, NGOs, Institutions - comprehensive)
ORGANIZATIONS = {
    # === INTERNATIONAL ORGANIZATIONS ===
    "united nations", "un", "who", "unesco", "unicef", "imf", "world bank",
    "world health organization", "world trade organization", "wto",
    "international monetary fund", "world food programme", "wfp",
    "international atomic energy agency", "iaea", "interpol",
    "international criminal court", "icc", "icj", "world court",
    "international committee of the red cross", "icrc", "red cross", "red crescent",
    "world economic forum", "wef", "oecd", "g7", "g20", "g77",
    "european union", "eu", "european central bank", "ecb",
    "african union", "au", "asean", "opec", "opec+", "apec", "brics",
    "arab league", "oic", "commonwealth", "nato", "osce",
    "amnesty international", "human rights watch", "hrw",
    "greenpeace", "doctors without borders", "msf", "oxfam", "care",
    "save the children", "world wildlife fund", "wwf", "iucn",
    "transparency international", "reporters without borders",
    # === TECH ACRONYMS & TERMS ===
    # AI & Machine Learning
    "ai", "artificial intelligence", "ml", "machine learning", "llm", "llms",
    "large language model", "gpt", "chatgpt", "gpt-4", "gpt-5", "claude",
    "generative ai", "gen ai", "neural network", "neural networks",
    "deep learning", "nlp", "natural language processing", "computer vision",
    "reinforcement learning", "supervised learning", "transformer",
    "diffusion model", "stable diffusion", "midjourney", "dall-e",
    "copilot", "gemini", "bard", "llama", "mistral", "perplexity",
    # VR/AR/XR
    "vr", "virtual reality", "ar", "augmented reality", "xr", "mixed reality",
    "metaverse", "oculus", "quest", "hololens", "vision pro", "spatial computing",
    # Connectivity & Infrastructure
    "iot", "internet of things", "5g", "6g", "wifi", "wi-fi", "broadband",
    "fiber optic", "starlink", "satellite internet", "edge computing",
    "cloud computing", "aws", "azure", "gcp", "data center", "data centers",
    "api", "apis", "saas", "paas", "iaas", "microservices", "kubernetes",
    "docker", "devops", "agile", "scrum",
    # Electric & Autonomous Vehicles
    "ev", "evs", "electric vehicle", "electric vehicles", "hybrid",
    "autonomous vehicle", "autonomous vehicles", "self-driving", "autopilot",
    "full self-driving", "fsd", "lidar", "adas", "vehicle-to-everything", "v2x",
    # Crypto & Blockchain
    "blockchain", "cryptocurrency", "cryptocurrencies", "crypto",
    "bitcoin", "btc", "ethereum", "eth", "solana", "cardano", "dogecoin",
    "stablecoin", "stablecoins", "usdt", "usdc", "defi", "decentralized finance",
    "nft", "nfts", "non-fungible token", "web3", "dao", "smart contract",
    "smart contracts", "mining", "proof of work", "proof of stake",
    # Cybersecurity
    "deepfake", "deepfakes", "cybersecurity", "cyber security", "infosec",
    "ransomware", "malware", "phishing", "spyware", "trojan", "botnet",
    "ddos", "zero-day", "exploit", "vulnerability", "data breach",
    "encryption", "end-to-end encryption", "vpn", "firewall", "antivirus",
    "two-factor", "2fa", "mfa", "biometric", "biometrics",
    # Hardware & Chips
    "semiconductor", "semiconductors", "chip", "chips", "microchip", "microchips",
    "cpu", "gpu", "gpus", "tpu", "processor", "processors", "silicon",
    "nanometer", "fab", "foundry", "tsmc", "asml", "arm", "risc-v", "quantum",
    "quantum computing", "quantum computer", "qubit", "qubits",
    # Software & Platforms
    "software", "hardware", "firmware", "app", "apps", "application",
    "platform", "platforms", "algorithm", "algorithms", "open source",
    "proprietary", "linux", "windows", "macos", "android", "ios",
    # Data & Analytics
    "big data", "data analytics", "data science", "database", "sql", "nosql",
    "data privacy", "gdpr", "ccpa", "cookies", "tracking", "surveillance",
    # Social Media & Content
    "social media", "streaming", "content moderation", "misinformation",
    "disinformation", "fake news", "bot", "bots", "troll", "viral",
    "influencer", "influencers", "creator economy", "monetization",
    # Emerging Tech
    "biotech", "biotechnology", "crispr", "gene editing", "mrna",
    "nanotechnology", "nanotech", "3d printing", "additive manufacturing",
    "robotics", "robot", "robots", "drone", "drones", "uav",
    "brain-computer interface", "bci", "neuralink", "wearable", "wearables",
    # === TECH COMPANIES ===
    # Big Tech / FAANG+
    "apple", "google", "alphabet", "microsoft", "amazon", "meta", "facebook",
    "twitter", "x corp", "tesla", "nvidia", "netflix",
    # AI Companies
    "openai", "anthropic", "deepmind", "google ai", "meta ai", "microsoft ai",
    "cohere", "stability ai", "inflection", "character ai", "hugging face",
    "scale ai", "databricks", "c3 ai", "soundhound", "jasper",
    "runway", "eleven labs", "synthesia", "replika", "adept",
    # Semiconductors & Hardware
    "intel", "amd", "nvidia", "qualcomm", "broadcom", "texas instruments",
    "micron", "western digital", "seagate", "sk hynix", "mediatek",
    "marvell", "on semiconductor", "analog devices", "nxp", "infineon",
    "arm holdings", "synopsys", "cadence", "lam research", "applied materials",
    # Enterprise Software
    "ibm", "oracle", "salesforce", "sap", "workday", "servicenow",
    "adobe", "intuit", "autodesk", "vmware", "splunk", "datadog",
    "mongodb", "elastic", "confluent", "hashicorp", "gitlab", "github",
    "atlassian", "asana", "monday", "notion", "airtable", "figma",
    # Cloud & Infrastructure
    "cisco", "juniper", "arista", "f5", "cloudflare", "fastly", "akamai",
    "digitalocean", "linode", "vultr", "rackspace", "equinix",
    # Hardware & Devices
    "dell", "hp", "hewlett packard", "hpe", "lenovo", "asus", "acer",
    "samsung", "sony", "lg", "panasonic", "toshiba", "sharp", "tcl",
    "huawei", "xiaomi", "oppo", "vivo", "oneplus", "realme", "honor",
    "logitech", "razer", "corsair", "steelseries",
    # Social Media & Content
    "tiktok", "bytedance", "snap", "snapchat", "pinterest", "reddit",
    "discord", "twitch", "youtube", "instagram", "whatsapp", "telegram",
    "signal", "wechat", "weibo", "line", "kakao",
    # Chinese Tech Giants
    "alibaba", "tencent", "baidu", "jd.com", "meituan", "pinduoduo",
    "didi", "nio", "xpeng", "li auto", "netease", "bilibili",
    "kuaishou", "ant group", "sea limited", "grab", "gojek",
    # E-commerce & Marketplaces
    "ebay", "etsy", "wayfair", "chewy", "wish", "mercadolibre",
    "coupang", "flipkart", "lazada", "shopee", "zalando",
    # Streaming & Entertainment
    "netflix", "spotify", "roku", "sonos", "pandora", "deezer",
    "hulu", "peacock", "paramount+", "discovery+", "crunchyroll",
    # Rideshare & Delivery
    "uber", "lyft", "airbnb", "doordash", "instacart", "grubhub",
    "deliveroo", "just eat", "bolt", "ola", "careem", "gett",
    # Fintech & Payments
    "paypal", "square", "block", "stripe", "coinbase", "robinhood",
    "klarna", "affirm", "afterpay", "marqeta", "plaid", "chime",
    "sofi", "revolut", "n26", "monzo", "wise", "adyen",
    "binance", "kraken", "gemini", "ftx", "celsius", "blockfi",
    # Collaboration & Productivity
    "zoom", "slack", "dropbox", "box", "docusign", "ringcentral",
    "twilio", "okta", "zscaler", "crowdstrike", "sentinelone",
    "shopify", "wix", "squarespace", "godaddy", "hubspot", "mailchimp",
    # Cybersecurity
    "palo alto networks", "fortinet", "check point", "fireeye", "mandiant",
    "mcafee", "norton", "symantec", "kaspersky", "bitdefender", "avast",
    "proofpoint", "mimecast", "tenable", "rapid7", "qualys",
    # Gaming Tech
    "unity", "roblox", "zynga", "king", "supercell", "niantic",
    "epic games", "valve", "steam", "ea", "ubisoft", "capcom",
    # Data & Analytics
    "snowflake", "palantir", "tableau", "alteryx", "domo", "qlik",
    "teradata", "informatica", "talend", "fivetran",
    # Health Tech
    "teladoc", "doximity", "veeva", "cerner", "epic systems",
    "fitbit", "peloton", "whoop", "oura", "garmin",
    # === FINANCE & BANKING ===
    "jpmorgan", "jpmorgan chase", "goldman sachs", "morgan stanley",
    "bank of america", "citigroup", "citibank", "wells fargo",
    "hsbc", "barclays", "deutsche bank", "ubs", "credit suisse",
    "bnp paribas", "societe generale", "santander", "ing",
    "blackrock", "vanguard", "fidelity", "state street", "schwab",
    "berkshire hathaway", "visa", "mastercard", "american express",
    # === ENERGY & OIL ===
    "exxonmobil", "exxon", "chevron", "shell", "bp", "totalenergies", "total",
    "conocophillips", "marathon", "valero", "phillips 66",
    "gazprom", "rosneft", "lukoil", "saudi aramco", "aramco",
    "petrochina", "sinopec", "cnooc", "petrobras", "equinor", "eni",
    # === AUTOMOTIVE ===
    "toyota", "volkswagen", "vw", "ford", "general motors", "gm",
    "honda", "nissan", "hyundai", "kia", "bmw", "mercedes", "mercedes-benz",
    "audi", "porsche", "ferrari", "lamborghini", "maserati",
    "stellantis", "chrysler", "jeep", "dodge", "fiat", "peugeot", "renault",
    "rivian", "lucid", "nio", "byd", "geely", "volvo",
    # === AEROSPACE & DEFENSE ===
    "boeing", "airbus", "lockheed martin", "raytheon", "northrop grumman",
    "general dynamics", "bae systems", "l3harris", "leidos",
    "spacex", "blue origin", "virgin galactic", "rocket lab",
    # === PHARMA & HEALTHCARE ===
    "pfizer", "johnson & johnson", "j&j", "moderna", "astrazeneca",
    "novartis", "roche", "merck", "sanofi", "gsk", "glaxosmithkline",
    "abbvie", "eli lilly", "bristol myers squibb", "amgen", "gilead",
    "unitedhealth", "anthem", "cigna", "humana", "cvs", "walgreens",
    # === RETAIL & CONSUMER ===
    "walmart", "costco", "target", "kroger", "home depot", "lowes",
    "nike", "adidas", "puma", "under armour", "lululemon",
    "coca-cola", "pepsi", "pepsico", "nestle", "unilever", "procter & gamble",
    "mcdonalds", "starbucks", "yum brands", "chipotle", "dominos",
    "lvmh", "gucci", "prada", "hermes", "chanel", "rolex",
    # === MEDIA & ENTERTAINMENT ===
    "disney", "warner bros", "universal", "paramount", "sony pictures",
    "netflix", "hbo", "hulu", "peacock", "discovery",
    "live nation", "spotify", "sirius xm", "iheartmedia",
    "electronic arts", "ea", "activision", "blizzard", "take-two",
    "epic games", "riot games", "valve", "nintendo", "playstation", "xbox",
    # === NEWS MEDIA ===
    "reuters", "associated press", "ap", "afp", "agence france-presse",
    "bbc", "cnn", "fox news", "msnbc", "nbc", "abc", "cbs", "pbs", "npr",
    "new york times", "washington post", "wall street journal", "wsj",
    "los angeles times", "chicago tribune", "usa today", "politico",
    "guardian", "times", "telegraph", "daily mail", "financial times", "ft",
    "economist", "bloomberg", "reuters", "al jazeera", "rt", "xinhua",
    "der spiegel", "le monde", "el pais", "corriere della sera",
    "sky news", "euronews", "dw", "france 24", "nhk", "abc australia",
    # === UNIVERSITIES ===
    "harvard", "yale", "princeton", "columbia", "cornell", "brown", "dartmouth", "penn",
    "mit", "stanford", "caltech", "berkeley", "ucla", "usc",
    "university of chicago", "duke", "northwestern", "johns hopkins",
    "oxford", "cambridge", "imperial college", "lse", "ucl",
    "eth zurich", "epfl", "sorbonne", "heidelberg", "tu munich",
    "university of tokyo", "kyoto university", "tsinghua", "peking university",
    "national university of singapore", "nus", "melbourne university",
    # === THINK TANKS & RESEARCH ===
    "brookings", "rand corporation", "cato institute", "heritage foundation",
    "council on foreign relations", "cfr", "chatham house", "carnegie",
    "peterson institute", "hoover institution", "american enterprise institute",
    # === SPORTS LEAGUES ===
    "nfl", "nba", "mlb", "nhl", "mls", "pga", "ufc", "wwe",
    "fifa", "uefa", "premier league", "la liga", "bundesliga", "serie a",
    "ioc", "olympic committee", "world athletics", "itf", "atp", "wta",
}

# Places & Landmarks (comprehensive)
PLACES = {
    # === US CITIES (Top 100+) ===
    "new york", "new york city", "nyc", "manhattan", "brooklyn", "queens", "bronx",
    "los angeles", "chicago", "houston", "phoenix", "philadelphia",
    "san antonio", "san diego", "dallas", "san jose", "austin",
    "jacksonville", "fort worth", "columbus", "charlotte", "san francisco",
    "indianapolis", "seattle", "denver", "washington", "washington dc", "dc",
    "boston", "el paso", "detroit", "nashville", "portland", "memphis",
    "oklahoma city", "las vegas", "louisville", "baltimore", "milwaukee",
    "albuquerque", "tucson", "fresno", "mesa", "sacramento", "atlanta",
    "kansas city", "colorado springs", "miami", "raleigh", "omaha",
    "long beach", "virginia beach", "oakland", "minneapolis", "tulsa",
    "tampa", "arlington", "new orleans", "wichita", "cleveland",
    "bakersfield", "aurora", "anaheim", "honolulu", "santa ana",
    "riverside", "corpus christi", "lexington", "st louis", "stockton",
    "pittsburgh", "anchorage", "cincinnati", "st paul", "newark",
    "greensboro", "plano", "henderson", "lincoln", "orlando",
    "jersey city", "chula vista", "buffalo", "fort wayne", "chandler",
    "st petersburg", "laredo", "durham", "irvine", "madison",
    "norfolk", "lubbock", "gilbert", "winston-salem", "glendale",
    "reno", "hialeah", "garland", "chesapeake", "irving", "north las vegas",
    "scottsdale", "baton rouge", "fremont", "richmond", "boise",
    "san bernardino", "birmingham", "spokane", "rochester", "modesto",
    "des moines", "oxnard", "tacoma", "fontana", "fayetteville",
    "moreno valley", "yonkers", "huntington beach", "salt lake city",
    "grand rapids", "amarillo", "montgomery", "little rock", "akron",
    "huntsville", "augusta", "port st lucie", "grand prairie", "tallahassee",
    "overland park", "tempe", "mckinney", "mobile", "cape coral", "shreveport",
    # === EUROPEAN CITIES ===
    "london", "manchester", "birmingham", "liverpool", "leeds", "sheffield",
    "bristol", "glasgow", "edinburgh", "cardiff", "belfast", "dublin",
    "newcastle", "nottingham", "southampton", "leicester", "portsmouth",
    "paris", "marseille", "lyon", "toulouse", "nice", "nantes",
    "strasbourg", "montpellier", "bordeaux", "lille", "rennes",
    "berlin", "hamburg", "munich", "cologne", "frankfurt", "stuttgart",
    "dusseldorf", "dortmund", "essen", "leipzig", "bremen", "dresden", "hanover",
    "rome", "milan", "naples", "turin", "palermo", "genoa", "bologna",
    "florence", "venice", "verona", "bari",
    "madrid", "barcelona", "valencia", "seville", "zaragoza", "malaga",
    "bilbao", "murcia", "palma",
    "amsterdam", "rotterdam", "the hague", "brussels", "antwerp",
    "vienna", "zurich", "geneva", "basel", "bern", "lisbon", "porto",
    "athens", "thessaloniki",
    "moscow", "st petersburg", "kyiv", "kiev", "kharkiv", "odesa", "odessa",
    "warsaw", "krakow", "lodz", "prague", "brno", "budapest",
    "bucharest", "sofia", "belgrade", "zagreb", "sarajevo", "skopje",
    "tirana", "pristina", "chisinau", "minsk", "vilnius", "riga", "tallinn",
    "stockholm", "gothenburg", "malmo", "oslo", "bergen", "copenhagen",
    "helsinki", "reykjavik",
    # === ASIAN CITIES ===
    "beijing", "shanghai", "guangzhou", "shenzhen", "chengdu", "hangzhou",
    "wuhan", "xian", "nanjing", "tianjin", "chongqing", "shenyang",
    "harbin", "dalian", "qingdao", "zhengzhou", "kunming", "changsha",
    "tokyo", "osaka", "kyoto", "yokohama", "nagoya", "sapporo", "kobe",
    "fukuoka", "kawasaki", "hiroshima", "sendai", "kitakyushu",
    "seoul", "busan", "incheon", "daegu", "daejeon", "gwangju", "ulsan",
    "delhi", "new delhi", "mumbai", "bombay", "bangalore", "bengaluru",
    "hyderabad", "chennai", "madras", "kolkata", "calcutta", "ahmedabad",
    "pune", "surat", "jaipur", "lucknow", "kanpur",
    "bangkok", "ho chi minh city", "saigon", "hanoi", "singapore",
    "kuala lumpur", "jakarta", "surabaya", "manila", "quezon city",
    "phnom penh", "yangon", "rangoon", "vientiane",
    "hong kong", "taipei", "kaohsiung", "macau", "ulaanbaatar",
    "karachi", "lahore", "islamabad", "dhaka", "chittagong",
    "colombo", "kathmandu", "kabul", "tashkent", "almaty", "astana",
    # === MIDDLE EAST CITIES ===
    "tehran", "baghdad", "basra", "mosul", "damascus", "aleppo",
    "jerusalem", "tel aviv", "haifa", "gaza city", "ramallah",
    "beirut", "amman", "riyadh", "jeddah", "mecca", "medina",
    "dubai", "abu dhabi", "doha", "kuwait city", "manama", "muscat",
    "sanaa", "aden", "ankara", "istanbul", "izmir", "antalya",
    # === AFRICAN CITIES ===
    "cairo", "alexandria", "giza", "lagos", "kano", "ibadan", "abuja",
    "johannesburg", "cape town", "durban", "pretoria", "nairobi", "mombasa",
    "addis ababa", "dar es salaam", "kampala", "kigali", "kinshasa",
    "luanda", "harare", "lusaka", "maputo", "accra", "dakar", "abidjan",
    "casablanca", "rabat", "algiers", "tunis", "tripoli", "khartoum",
    # === AMERICAS (non-US) ===
    "toronto", "montreal", "vancouver", "calgary", "edmonton", "ottawa",
    "winnipeg", "quebec city", "hamilton", "halifax",
    "mexico city", "guadalajara", "monterrey", "tijuana", "cancun",
    "guatemala city", "san salvador", "tegucigalpa", "managua",
    "panama city", "havana", "santo domingo", "san juan",
    "kingston", "port-au-prince",
    "sao paulo", "rio de janeiro", "brasilia", "salvador", "fortaleza",
    "buenos aires", "cordoba", "rosario", "bogota", "medellin", "cali",
    "lima", "santiago", "caracas", "maracaibo", "quito", "guayaquil",
    "la paz", "montevideo", "asuncion", "georgetown", "paramaribo",
    # === OCEANIA ===
    "sydney", "melbourne", "brisbane", "perth", "adelaide", "canberra",
    "auckland", "wellington", "christchurch", "suva", "port moresby",
    # === LANDMARKS & REGIONS ===
    "capitol hill", "wall street", "silicon valley", "hollywood",
    "times square", "central park", "ground zero", "las vegas strip",
    "golden gate", "liberty island", "pearl harbor", "mount rushmore",
    "grand canyon", "yellowstone", "yosemite", "niagara falls",
    "red square", "tiananmen square", "forbidden city", "great wall",
    "eiffel tower", "big ben", "buckingham palace", "westminster",
    "colosseum", "vatican city", "notre dame", "louvre", "versailles",
    "tower of london", "stonehenge", "acropolis", "parthenon",
    "taj mahal", "angkor wat", "machu picchu", "christ the redeemer",
    "kremlin", "downing street", "champs elysees", "brandenburg gate",
    "white house", "pentagon", "capitol building",
    "10 downing street", "elysee palace", "reichstag", "european parliament",
    "west bank", "gaza strip", "golan heights", "crimea", "donbas", "donetsk",
    "luhansk", "transnistria", "nagorno-karabakh", "south ossetia", "abkhazia",
    "kashmir", "tibet", "xinjiang",
    "middle east", "near east", "far east", "southeast asia", "south asia",
    "central asia", "east asia", "north africa", "sub-saharan africa",
    "western europe", "eastern europe", "northern europe", "southern europe",
    "latin america", "central america", "caribbean", "south america",
    "north america", "oceania", "australasia", "scandinavia", "balkans",
    "baltic states", "caucasus", "persian gulf", "arabian peninsula",
    "levant", "maghreb", "sahel",
    "atlantic", "pacific", "indian ocean", "arctic ocean", "antarctic",
    "mediterranean", "caribbean sea", "south china sea", "east china sea",
    "sea of japan", "black sea", "caspian sea", "red sea", "dead sea",
    "baltic sea", "north sea", "arabian sea", "bay of bengal",
    "gulf of mexico", "gulf of aden", "taiwan strait",
    "strait of hormuz", "strait of malacca", "english channel",
    "suez canal", "panama canal", "bosphorus",
}

# Events & Conflicts (comprehensive)
EVENTS = {
    # === WORLD WARS ===
    "world war", "world war i", "world war ii", "wwi", "wwii",
    "first world war", "second world war", "great war",
    # === COLD WAR ERA ===
    "cold war", "iron curtain", "berlin wall", "cuban missile crisis",
    "korean war", "vietnam war", "soviet-afghan war",
    "bay of pigs", "space race", "arms race",
    # === MIDDLE EAST CONFLICTS ===
    "gulf war", "iraq war", "iran-iraq war",
    "war on terror", "afghanistan war", "operation enduring freedom",
    "operation iraqi freedom", "desert storm", "desert shield",
    "six day war", "yom kippur war", "arab-israeli war",
    "gaza war", "gaza conflict", "intifada", "first intifada", "second intifada",
    "lebanon war", "syrian civil war", "yemen civil war", "yemeni civil war",
    "libyan civil war", "isis insurgency",
    # === EUROPE/RUSSIA CONFLICTS ===
    "ukraine war", "russian invasion", "invasion of ukraine",
    "crimean annexation", "donbas war", "chechen war",
    "bosnian war", "kosovo war", "yugoslav wars", "balkan wars",
    "nagorno-karabakh war", "georgian war", "russo-georgian war",
    # === AFRICAN CONFLICTS ===
    "rwandan genocide", "darfur", "somali civil war", "ethiopian civil war",
    "tigray war", "congo war", "liberian civil war", "sierra leone civil war",
    "sudanese civil war", "south sudan civil war", "boko haram insurgency",
    # === ASIAN CONFLICTS ===
    "chinese civil war", "indo-pakistani war", "kashmir conflict",
    "sri lankan civil war", "rohingya crisis", "myanmar coup",
    "tiananmen square massacre", "tiananmen",
    # === AMERICAS CONFLICTS ===
    "american civil war", "mexican revolution",
    "cuban revolution", "nicaraguan revolution",
    "colombian conflict", "farc insurgency", "drug war",
    # === HISTORICAL EVENTS ===
    "french revolution", "russian revolution", "october revolution",
    "industrial revolution", "american revolution",
    "napoleonic wars", "hundred years war", "thirty years war",
    "crusades", "spanish civil war",
    # === TERRORISM & ATTACKS ===
    "9/11", "september 11", "september 11 attacks",
    "january 6", "jan 6", "january 6 insurrection", "capitol riot",
    "october 7", "october 7 attack", "hamas attack",
    "boston marathon bombing", "london bombings", "7/7",
    "paris attacks", "bataclan", "charlie hebdo",
    "madrid bombings", "mumbai attacks", "bali bombings",
    "oklahoma city bombing", "manchester arena bombing",
    "christchurch shooting", "las vegas shooting",
    # === DISASTERS & CRISES ===
    "covid", "covid-19", "pandemic", "coronavirus", "corona",
    "sars", "mers", "ebola", "swine flu", "bird flu",
    "financial crisis", "great recession", "subprime crisis",
    "fukushima", "chernobyl", "three mile island",
    "deepwater horizon", "exxon valdez",
    "hurricane katrina", "hurricane sandy", "hurricane maria",
    "indian ocean tsunami", "japan tsunami", "haiti earthquake",
    "california wildfires", "australian bushfires",
    # === POLITICAL EVENTS ===
    "brexit", "arab spring", "color revolution", "velvet revolution",
    "orange revolution", "euromaidan", "maidan",
    "tiananmen square", "hong kong protests", "umbrella movement",
    "watergate", "iran-contra", "monica lewinsky", "impeachment",
    "mueller investigation", "russia investigation",
    # === TREATIES & AGREEMENTS ===
    "paris agreement", "paris climate accord", "kyoto protocol",
    "geneva convention", "geneva conventions",
    "camp david", "camp david accords", "oslo accords",
    "dayton agreement", "good friday agreement", "belfast agreement",
    "iran nuclear deal", "jcpoa", "new start", "inf treaty",
    "versailles treaty", "treaty of versailles",
    "maastricht treaty", "lisbon treaty", "rome treaty",
    "abraham accords", "normalization agreement",
    # === SUMMITS & CONFERENCES ===
    "g7", "g7 summit", "g8", "g20", "g20 summit",
    "cop26", "cop27", "cop28", "cop29", "climate summit",
    "un general assembly", "unga", "security council",
    "davos", "world economic forum", "apec summit", "asean summit",
    "nato summit", "eu summit", "munich security conference",
    # === ELECTIONS ===
    "presidential election", "midterm elections", "general election",
    "brexit referendum", "scottish referendum", "quebec referendum",
    # === SPORTS EVENTS ===
    "olympics", "olympic games", "summer olympics", "winter olympics",
    "paralympics", "world cup", "fifa world cup", "euro",
    "super bowl", "world series", "nba finals", "stanley cup",
    "wimbledon", "us open", "french open", "australian open",
    "tour de france", "formula 1", "f1", "grand prix",
    "commonwealth games", "asian games", "pan american games",
}
